# action.yml
name: trigger-dispatch
runs:
  using: "composite"
  steps:
    - run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ inputs.token }}" \
          https://api.github.com/repos/${{ inputs.owner }}/${{ inputs.repo }}/dispatches \
          -d '{"event_type":"custom-trigger"}'
