name: Trigger Workflow

on:
  push:
    branches: [main]

jobs:
  trigger-other:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: |
          curl -X POST https://api.github.com/repos/<OWNER>/<REPO>/dispatches \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"event_type":"custom-trigger"}'
